### ISSUE TITLE
difficulty parameter is not actually used in game method

### ISSUE THREAD

**Issue by DrewMcArthur** [4zv4l/wordle#1]
in [`main.go:148`](https://github.com/4zv4l/wordle/blob/main/main.go#L148), `difficulty` is passed as a parameter to define how many tries the user gets to guess.  However, the game is capped at [5 guesses by the condition on line 161](https://github.com/4zv4l/wordle/blob/main/main.go#L161).  the hardcoded number 5 on this line should be replaced with `difficulty` to allow more guesses when playing easier modes.

**Comment by 4zv4l** [comment]
Yeah thank you very much ! Just updated it ^^
